### ISSUE TITLE
Replace Elnode with other server

### ISSUE THREAD

**Issue by rejeep** [cask/servant#15]
Elnode's version on Melpa is almost a year old and it's not likely that there ever will be a recently updated and stable version available.

There are other alternatives to Elnode, namely:
- https://github.com/eschulte/emacs-web-server 
- https://github.com/skeeto/emacs-web-server

Cask `v0.6` will depend on Servant, hence also on Elnode. In it's current state, I really don't want to depend on Elnode.

I haven't investigated the mentioned alternatives and I don't know if they would work out here, but I think it's worth a try.

**Comment by swsnr** [comment]
Why will Cask depend on Servant?!

Imho we should get rid of any Emacs webserver.  After our not so nice experiences with elnode I feel confirmed, that Emacs Lisp is a good language for such stuff. Too many side effects, too much hidden state, too much implicit processing.

Instead, I'd use Emacs for the packaging part, namely creating the archive index, and then feed the resulting directory to a simple web server. For instance, Python has one in its standard library, which can be run from the command line.

**Comment by rejeep** [comment]
> Why will Cask depend on Servant?!

To allow this in the Cask-file:

``` lisp
(depends-on "foo" :git "git@git-stuff.com/foo.git")
```

Cask will download, build a package and serve using Servant.

> Imho we should get rid of any Emacs webserver.

I would obviously like to write as much of this as possible in Emacs Lisp. It actually does work quite well (see https://github.com/cask/cask/commit/6cd0ac20c1875d8763f2c25c50c19e194a4bd13d). At least in `24.3.1`.

I know it hasn't been flawless and if you know of a better solution I'm open for suggestions.

> For instance, Python has one in its standard library, which can be run from the command line.

Would it be possible write a Servant clone using that? How much work would it require?

**Comment by swsnr** [comment]
@rejeep Cool!

We can try an Emacs Lisp server as well.   I'm probably just a little damage by my Elnode experiences.

In that case, I'd vote for @skeeto's server.  I don't have  any convincing technical reason (I didn't look at either implementation), but he has a good reputation as Emacs Lisp developer and maintainer, imho.

As for Python, it shouldn't be too difficult to port Servant.  We'd just need to write the package archive index to the corresponding file in the package directory, and run `python -m SimpleHTTPServer` from that directory.

In either case, I'm currently short of time, and can't tackle that any time soon.

**Comment by rejeep** [comment]
> We can try an Emacs Lisp server as well. I'm probably just a little damage by my Elnode experiences.

Yes, me too. But I just realized that the Elnode version on Melpa is almost a year old. Hopefully the new version will improve.

So let's start with the Emacs server since I've already implemented it. If we realize in the future that it does not work, we simply rewrite it in Python.

**Comment by swsnr** [comment]
@rejeep :+1:

**Comment by eschulte** [comment]
Author of https://github.com/eschulte/emacs-web-server here.  I just stumbled across this thread.  If you're already working with elnode it should be easy to transition to my web server (I wrote it to replace elnode in some of my own projects).  Emacs web server uses a similar "handler" based design.  Check out the manual (http://eschulte.github.io/emacs-web-server/index.html#Top) for more information and let me know if you run into any problems or have any questions.

**Comment by rejeep** [comment]
@eschulte Tried it out a bit and it seems to work. I cant find the package version? There are no header comments nor a `-pkg.el` file.

**Comment by rejeep** [comment]
See https://github.com/cask/servant/pull/17

**Comment by eschulte** [comment]
I just added a packaging Makefile target so `make package` will now generate an Emacs package for web-server.

**Comment by rejeep** [comment]
Why not simply add the standard headers?

**Comment by eschulte** [comment]
Because the headers only work for "Simple Packages", not multi-file packages.

**Comment by rejeep** [comment]
You could use a `-pkg.el` file or Cask! :)

**Comment by eschulte** [comment]
I actually write a -pkg.el file from the Makefile (see https://github.com/eschulte/emacs-web-server/blob/master/Makefile#L41) when building the package tarball.  If it would be useful to other tools (e.g., cask) I'd be happy to commit the -pkg.el file to the repo, rather than just generating it on the fly.

**Comment by rejeep** [comment]
If you use Cask I would add proper header comments to one file and then use the Cask `package-file` directive. That can also generate a `-pkg.el` file for you!

**Comment by eschulte** [comment]
Fair enough, it'd be good to include this information in the header regardless of packaging.  I now have included the standard headers.  Cheers,

**Comment by rejeep** [comment]
Just make sure Melpa can handle this, I cant remember

**Comment by eschulte** [comment]
Checked, works.
