### ISSUE TITLE
Use EPL for package interaction

### ISSUE THREAD

**Issue by rejeep** [cask/servant#3]
https://github.com/cask/epl

**Comment by swsnr** [comment]
Was actually quite simple :)

As for the other code, that extracts version information from TARs and `-pkg` files, I think this should become part of EPL, as part of `epl-package-from-file` and `epl-package-from-descriptor-file` respectively.

**Comment by rejeep** [comment]
Nice! :)

**Comment by swsnr** [comment]
@rejeep EPL now provides functions to create packages from tars and descriptors.  Note that unlike the current code in servant.el, TARs without a `-pkg.el` file are not supported.  package.el doesn't support them either, so I don't think that's an issue.

**Comment by swsnr** [comment]
@rejeep I'll wait for EPL being updated in MELPA, and update servant.

**Comment by rejeep** [comment]
Didn't know about the tar-function in package.el. Like always, you know every dirty little secret of Emacs :)

**Comment by swsnr** [comment]
@rejeep Well, I'm just reading the package.el source code.  It's not the nicest thing ever (though it greatly improved in trunk), but I think EPL should stay as close as possible to package.el and re-use as much code as possible.  Otherwise we'll run into incompatibilities sooner or later…

**Comment by rejeep** [comment]
Yes, agreed!
